const ACTIONTYPE = {
    ADDQUIZ: "ADDQUIZ",
    PLAYQUIZ: "PLAYQUIZ",
    GETNAME: "GETNAME",
    GETANSWER: "GETANSWER",
    RESET: "RESET",
    TOGGLEACTIVE: "TOGGLEACTIVE",
    DELETEQUIZ: "DELETEQUIZ",
};

export default ACTIONTYPE;